deployment_target = '13.0'

target 'iosApp' do
  use_modular_headers!
  platform :ios, deployment_target
  pod 'SDWebImageSwiftUI'
  pod 'AlertToast'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end